import Head from 'next/head'
import { Inter } from 'next/font/google'
import 'bootstrap/dist/css/bootstrap.min.css'
import { useContext, useEffect, useState } from 'react'
import Navbar from '@/components/Navbar'
import StateContext from '../../Contexts/StateContext'
import Main from '@/components/Main'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  
  const { setNavbarData , NavbarData} = useContext(StateContext)
  
    

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className='container-fluid vh-100 '>
            <div className='container border'>
              <div className='nav border w-100'>
              <Navbar/>
              </div>
              <div className='main border'>
              <Main/>
              </div>
            </div>
        </div>
      </main>
    </>
  )
}
